# Generated by Django 6.0.1 on 2026-01-28 18:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(help_text='Введите инвентарный номер', max_length=50, unique=True, verbose_name='Инвентарный номер')),
                ('name', models.CharField(help_text='Введите название оборудования', max_length=75, verbose_name='Название')),
                ('manufacturer', models.CharField(help_text='Введите производителя', max_length=75, verbose_name='Производитель')),
                ('model', models.CharField(help_text='Введите модель оборудования', max_length=75, verbose_name='Модель')),
                ('serial_number', models.CharField(help_text='Введите серийный номер', max_length=50, unique=True, verbose_name='Серийный номер')),
                ('warranty_expiry_date', models.DateField(blank=True, help_text='Введите дату окончания гарантии', null=True, verbose_name='Дата окончания гарантии')),
                ('notes', models.TextField(blank=True, help_text='Введите примечания', validators=[django.core.validators.MaxLengthValidator(10000)], verbose_name='Примечания')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(help_text='Введите название зоны', max_length=50, verbose_name='Зона')),
                ('workstation_number', models.CharField(help_text='Введите номер игрового места', max_length=10, verbose_name='Номер игрового места')),
                ('description', models.TextField(blank=True, help_text='Добавьте описание для места', validators=[django.core.validators.MaxLengthValidator(10000)], verbose_name='Описание местоположения')),
            ],
            options={
                'verbose_name': 'Местоположение',
                'verbose_name_plural': 'Местоположения',
                'ordering': ['zone_name', 'workstation_number'],
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_name', models.CharField(help_text='Введите название характеристики', max_length=50, verbose_name='Название характеристики')),
                ('spec_value', models.CharField(help_text='Введите значение характеристики', max_length=50, verbose_name='Значение')),
                ('unit', models.CharField(help_text='Введите единицу измерения', max_length=50, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
                'ordering': ['spec_name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(choices=[('active', 'Активно'), ('inactive', 'Неактивно'), ('maintenance', 'На обслуживании')], help_text='Выберите статус оборудования', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(blank=True, help_text='Добавьте описание', validators=[django.core.validators.MaxLengthValidator(10000)], verbose_name='Описание')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kursovaya.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Статус оборудования',
                'verbose_name_plural': 'Статусы оборудования',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(help_text='Введите тип оборудования', max_length=50, verbose_name='Тип оборудования')),
                ('category', models.CharField(help_text='Введите категорию оборудования', max_length=50, verbose_name='Категория')),
                ('description', models.TextField(blank=True, help_text='Добавьте описание оборудования', verbose_name='Описание оборудования')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kursovaya.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Тип оборудования',
                'verbose_name_plural': 'Типы оборудования',
                'ordering': ['category', 'type_name'],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='current_location',
            field=models.ForeignKey(help_text='Выберите текущее местоположение', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kursovaya.location', verbose_name='Текущее местоположение'),
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_date', models.DateField(help_text='Введите дату перемещения', verbose_name='Дата перемещения')),
                ('reason', models.TextField(help_text='Введите причину перемещения', validators=[django.core.validators.MaxLengthValidator(10000)], verbose_name='Причина')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kursovaya.equipment', verbose_name='Оборудование')),
                ('from_location', models.ForeignKey(help_text='Выберите исходное местоположение', on_delete=django.db.models.deletion.CASCADE, related_name='movements_from', to='kursovaya.location', verbose_name='Откуда')),
                ('responsible_user', models.ForeignKey(help_text='Выберите ответственного пользователя', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('to_location', models.ForeignKey(help_text='Выберите новое местоположение', on_delete=django.db.models.deletion.CASCADE, related_name='movements_to', to='kursovaya.location', verbose_name='Куда')),
            ],
            options={
                'verbose_name': 'Перемещение',
                'verbose_name_plural': 'Перемещения',
                'ordering': ['-movement_date'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kursovaya.equipment', verbose_name='Оборудование')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kursovaya.specification', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Характеристика оборудования',
                'verbose_name_plural': 'Характеристики оборудования',
            },
        ),
        migrations.CreateModel(
            name='WriteOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('write_off_date', models.DateField(help_text='Введите дату списания', verbose_name='Дата списания')),
                ('reason', models.TextField(help_text='Введите причину списания', validators=[django.core.validators.MaxLengthValidator(10000)], verbose_name='Причина')),
                ('act_number', models.IntegerField(help_text='Введите номер акта списания', unique=True, verbose_name='Номер акта')),
                ('notes', models.TextField(blank=True, help_text='Введите примечания к списанию', validators=[django.core.validators.MaxLengthValidator(10000)], verbose_name='Примечания')),
                ('approved_by', models.ForeignKey(help_text='Выберите утвердившего пользователя', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Утвердил')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kursovaya.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Списание',
                'verbose_name_plural': 'Списания',
                'ordering': ['-write_off_date'],
            },
        ),
    ]
